# Generated by Django 5.2.15 on 2026-06-08 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="OTPService",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("platform", models.CharField(max_length=50)),
                ("country_code", models.CharField(max_length=10)),
                ("country_name", models.CharField(max_length=100)),
                (
                    "provider",
                    models.CharField(
                        choices=[("smspool", "SMSPool"), ("5sim", "5sim")],
                        max_length=20,
                    ),
                ),
                ("provider_service_id", models.CharField(max_length=100)),
                ("cost_price", models.DecimalField(decimal_places=4, max_digits=10)),
                ("sell_price", models.DecimalField(decimal_places=4, max_digits=10)),
                ("is_active", models.BooleanField(default=True)),
                ("synced_at", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="SMMService",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("provider_service_id", models.CharField(max_length=50)),
                ("name", models.CharField(max_length=255)),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("tiktok", "TikTok"),
                            ("instagram", "Instagram"),
                            ("facebook", "Facebook"),
                            ("youtube", "YouTube"),
                            ("twitter", "Twitter/X"),
                            ("whatsapp", "WhatsApp"),
                            ("telegram", "Telegram"),
                            ("google", "Google"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("followers", "Followers"),
                            ("likes", "Likes"),
                            ("views", "Views"),
                            ("comments", "Comments"),
                            ("shares", "Shares"),
                        ],
                        max_length=50,
                    ),
                ),
                ("cost_per_1000", models.DecimalField(decimal_places=4, max_digits=10)),
                ("sell_per_1000", models.DecimalField(decimal_places=4, max_digits=10)),
                ("min_quantity", models.IntegerField()),
                ("max_quantity", models.IntegerField()),
                ("is_active", models.BooleanField(default=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("synced_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
