# Generated by Django 5.2.15 on 2026-06-08 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("services", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="OTPOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("platform", models.CharField(max_length=50)),
                ("country_code", models.CharField(max_length=10)),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                ("otp_code", models.CharField(blank=True, max_length=20, null=True)),
                ("provider", models.CharField(max_length=20)),
                (
                    "provider_session_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("cost_price", models.DecimalField(decimal_places=4, max_digits=10)),
                ("sell_price", models.DecimalField(decimal_places=4, max_digits=10)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending_payment", "Pending payment"),
                            ("paid", "Paid"),
                            ("waiting_sms", "Waiting for SMS"),
                            ("received", "Received"),
                            ("expired", "Expired"),
                            ("cancelled", "Cancelled"),
                            ("refunded", "Refunded"),
                        ],
                        default="pending_payment",
                        max_length=20,
                    ),
                ),
                (
                    "customer_email",
                    models.EmailField(blank=True, max_length=255, null=True),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("cryptomus", "CryptoMus"),
                            ("flutterwave", "Flutterwave"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "payment_ref",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="orders",
                        to="services.otpservice",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SMMOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("target_url", models.TextField()),
                ("quantity", models.IntegerField()),
                ("cost_price", models.DecimalField(decimal_places=4, max_digits=10)),
                ("sell_price", models.DecimalField(decimal_places=4, max_digits=10)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending_payment", "Pending payment"),
                            ("paid", "Paid"),
                            ("processing", "Processing"),
                            ("in_progress", "In progress"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("refunded", "Refunded"),
                        ],
                        default="pending_payment",
                        max_length=20,
                    ),
                ),
                (
                    "provider_order_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "customer_email",
                    models.EmailField(blank=True, max_length=255, null=True),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("cryptomus", "CryptoMus"),
                            ("flutterwave", "Flutterwave"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "payment_ref",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="orders",
                        to="services.smmservice",
                    ),
                ),
            ],
        ),
    ]
