# Generated by Django 5.2.15 on 2026-06-13 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_otporder_payment_method_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otporder',
            name='status',
            field=models.CharField(choices=[('pending_payment', 'Pending payment'), ('paid', 'Paid'), ('waiting_sms', 'Waiting for SMS'), ('received', 'Received'), ('expired', 'Expired'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], default='pending_payment', max_length=20),
        ),
    ]
