# Generated by Django 4.2.13 on 2026-06-10 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("smmfollowers_api_key", models.CharField(blank=True, max_length=255)),
                ("smspool_api_key", models.CharField(blank=True, max_length=255)),
                ("fivesim_api_key", models.CharField(blank=True, max_length=255)),
                ("cryptomus_merchant_id", models.CharField(blank=True, max_length=255)),
                ("cryptomus_payment_key", models.CharField(blank=True, max_length=255)),
                (
                    "flutterwave_public_key",
                    models.CharField(blank=True, max_length=255),
                ),
                (
                    "flutterwave_secret_key",
                    models.CharField(blank=True, max_length=255),
                ),
                (
                    "flutterwave_webhook_hash",
                    models.CharField(blank=True, max_length=255),
                ),
            ],
            options={
                "verbose_name": "Site Settings",
            },
        ),
    ]
