# Generated by Django 4.2.13 on 2026-06-10 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("admin_panel", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="sitesettings",
            old_name="flutterwave_public_key",
            new_name="notchpay_public_key",
        ),
        migrations.RenameField(
            model_name="sitesettings",
            old_name="flutterwave_secret_key",
            new_name="notchpay_secret_key",
        ),
        migrations.RemoveField(
            model_name="sitesettings",
            name="flutterwave_webhook_hash",
        ),
    ]
