# Generated by Django 4.2.13 on 2026-06-10 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="method",
            field=models.CharField(
                choices=[("cryptomus", "CryptoMus"), ("notchpay", "NotchPay")],
                max_length=20,
            ),
        ),
    ]
