from django.urls import path

from . import views

urlpatterns = [
    path("auth/login/", views.AdminLoginView.as_view(), name="admin-login"),
    path("auth/login", views.AdminLoginView.as_view(), name="admin-login-noslash"),
    path("auth/refresh/", views.AdminTokenRefreshView.as_view(), name="admin-token-refresh"),
    path("auth/refresh", views.AdminTokenRefreshView.as_view(), name="admin-token-refresh-noslash"),
    path("dashboard/", views.DashboardView.as_view(), name="admin-dashboard"),
    path("dashboard", views.DashboardView.as_view(), name="admin-dashboard-noslash"),
    path("orders/", views.AdminOrderListView.as_view(), name="admin-order-list"),
    path("orders", views.AdminOrderListView.as_view(), name="admin-order-list-noslash"),
    path("orders/<str:order_id>/", views.AdminOrderDetailView.as_view(), name="admin-order-detail"),
    path("orders/<str:order_id>", views.AdminOrderDetailView.as_view(), name="admin-order-detail-noslash"),
    path("orders/<str:order_id>/refund/", views.AdminOrderRefundView.as_view(), name="admin-order-refund"),
    path("orders/<str:order_id>/refund", views.AdminOrderRefundView.as_view(), name="admin-order-refund-noslash"),
    path("orders/<str:order_id>/retry/", views.AdminOrderRetryView.as_view(), name="admin-order-retry"),
    path("orders/<str:order_id>/retry", views.AdminOrderRetryView.as_view(), name="admin-order-retry-noslash"),
    path("services/smm/", views.AdminSMMServiceListView.as_view(), name="admin-smm-service-list"),
    path("services/smm", views.AdminSMMServiceListView.as_view(), name="admin-smm-service-list-noslash"),
    path("services/smm/<int:pk>/", views.AdminSMMServiceDetailView.as_view(), name="admin-smm-service-detail"),
    path("services/smm/<int:pk>", views.AdminSMMServiceDetailView.as_view(), name="admin-smm-service-detail-noslash"),
    path("services/smm/sync/", views.AdminSMMServiceSyncView.as_view(), name="admin-smm-service-sync"),
    path("services/smm/sync", views.AdminSMMServiceSyncView.as_view(), name="admin-smm-service-sync-noslash"),
    path("services/otp/", views.AdminOTPServiceListView.as_view(), name="admin-otp-service-list"),
    path("services/otp", views.AdminOTPServiceListView.as_view(), name="admin-otp-service-list-noslash"),
    path("services/otp/<int:pk>/", views.AdminOTPServiceDetailView.as_view(), name="admin-otp-service-detail"),
    path("services/otp/<int:pk>", views.AdminOTPServiceDetailView.as_view(), name="admin-otp-service-detail-noslash"),
    path("services/otp/sync/", views.AdminOTPServiceSyncView.as_view(), name="admin-otp-service-sync"),
    path("services/otp/sync", views.AdminOTPServiceSyncView.as_view(), name="admin-otp-service-sync-noslash"),
    path("analytics/", views.AdminAnalyticsView.as_view(), name="admin-analytics"),
    path("analytics", views.AdminAnalyticsView.as_view(), name="admin-analytics-noslash"),
    path("settings/", views.AdminSettingsView.as_view(), name="admin-settings"),
    path("settings", views.AdminSettingsView.as_view(), name="admin-settings-noslash"),
]
